apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define the base resources that will be customized
resources:
  - ../../base

# Define patches to apply
patches:
  - path: patches/deployment_patch.yaml
    target:
      kind: Deployment
      name: your-app

